const d100cryomancy = [
  "A sharp cold runs through your mind. Your veins glow blue for a brief moment, as the cold forces you to calm and focus your sorcerous energy. You regain a 2nd-level or 2 1st-level spell slots (your choice).",
  "You cast the Armor of Agathys spell on yourself at 3rd-level.",
  "Your fingers and toes become webbed for the next 1d6 days. During this time, you gain a swimming speed equal to your walking speed. If you already have a swimming speed, it is doubled.",
  "You are unable to speak for the next 1d10 minutes as your mouth freezes shut with ice.",
  "Your skin becomes covered in a thin layer of rime and for the next 24 hours, you become resistant to Slashing, Piercing, and Cold damage. However, you become vulnerable to Bludgeoning and Fire damage.",
  "You summon a Water Elemental (controlled by the DM) within 10 feet of you in an unoccupied space. Roll 1d100. On an even number, the elemental is friendly towards you and your allies. On an uneven number, the elemental is hostile towards you and your allies.",
  "1d6 discs of ice appear in your hands. You can throw the discs at a target, using your spell attack bonus to make an attack with the disc. Upon impact, a disc deals 2d6 slashing damage and 2d6 cold damage. The discs last for 1d4 hours and shatter upon impact with a target.",
  "You cast Fog Cloud centered on yourself.",
  "For the next 1d10 minutes, all spells you cast that deal either acid, fire, lightning, poison or thunder damage instead deal cold damage.",
  "You cast Polymorph on the creature closest to you. If they fail the saving throw, you turn them into a white raven with ice blue eyes.",
  "Your skin becomes wet and slippery for the next 1d4 hours. During this time, you have advantage on all checks made to escape a grapple. Additionally, you have advantage on Dexterity saving throws.",
  "You cast the Hold Person spell on the creature closest to you. If they fail their saving throw, you freeze them solid for the duration of the spell. While frozen solid, they are still under the effects of the spell, but have resistance to fire damage.",
  "For the next 1d4 hours, you can cast the Stone Shape spell without expending a spell slot. However, you cannot manipulate stone with the spell - only ice and snow.",
  "You become the personification of frost for the next 2d4 days. During this time, whenever you touch another creature, they take 1d6 cold damage.",
  "It begins to snow in a 30 foot radius centered on you for the next hour.",
  "You stink heavily of fish and salt for the next 1d6 days.",
  "A freezing chill runs through your body and freezes you to the bone. You take 2d8 cold damage and your movement is halved for the next 1d6 hours.",
  "A cloak of dark ice and rime wraps around you. You gains the benefits of the Pass Without Trace spell for the next hour.",
  "You cast Wall of Water directly in front of you. The wall is 30 feet long, 10 feet high and 1 foot thick.",
  "Choose a creature. For the next hour, that creature can switch between their normal body and a mist-like form as if under the effects of the Gaseous Form spell.",
  "You cast the Slow spell centered on yourself.",
  "Fish-like gills appear alongside your neck. For the next 1d4 hours, you can breathe underwater.",
  "Your hands become covered in slick ice. You have disadvantage on all Sleight of Hand checks and Dexterity saving throws for the next hour.",
  "Your eyes become piercing blue for the next 1d4 days. You gain advantage on all Intimidation checks for this duration.",
  "You cast the Cone of Cold spell at 5th level. Treat yourself as being within the spell's area of effect.",
  "Your skin turns blue and you grow a mighty beard that would make a frost giant jealous. A remove curse spell can end this effect.",
  "Your body becomes icy cold. For the next 1d8+2 days, you gain resistance to cold damage.",
  "For the next hour, you can only speak Aquan. Additionally, the only spells you can cast, which require a verbal component, are the ones dealing cold damage or able to manipulate water or ice.",
  "An ice spike protrudes from your chest and explodes - damaging only you. You take 2d12 cold damage and absorb the power of the raw magic, regaining 1d4 Sorcery points.",
  "You summon a shield of ice, circling around you for the next 10 minutes. During this time, you gain a +2 to bonus to your AC.",
  "Your eyes become covered in a thick fog. You're considered Blinded as if affected by the Blindness/Deafness spell for the next 1d4 minutes.",
  "You cast Polymorph on yourself. If you fail the saving throw, you turn into a Winter Wolf for the spell's duration.",
  "All non-magical liquids on and around you in a 10 foot radius freezes solid.",
  "You emit an explosion of hail around you in a 20 foot radius. All creatures within range must make a Dexterity saving throw DC 16. On a failure, the creature takes 1d10 piercing damage and 1d10 cold damage. On a success, the creature takes half damage.",
  "You can cast the Control Water spell without expending a spell slot once within the next 24 hours.",
  "You summon a spear of ice. You can throw the spear to cast Ice Knife as a 3rd level spell.",
  "You cast the Arms of Hadar spell as a 2nd-level spell. Instead of necrotic damage, the spell deals cold damage and the tendrils resemble that of an octopus.",
  "All living creatures around you in a 20 foot radius have their bodily warmth drained from them, dealing 2d6 cold damage to all creatures in the radius (except you). You, on the other hand, feel warm and comfortable. You regain hit points equal to half the sum of the cold damage dealt.",
  "Long, jagged icicles grow out of your fingernails. For the next hour, you can use a bonus action to hurl an icicle, casting Ice Knife as a 1st-level spell.",
  "Your skin is covered with runes in Giant - all the runes are different words for ice and frost. For the next 10 minutes, your melee weapon attacks deal an additional 1d6 cold damage.",
  "All creature within 30 feet of you must make a Wisdom saving throw against your spell DC. If they fail, they see you as a powerful, icy god(dess) of wrath and winter and become frightened by you for 1 minute. On a success, a creature is unaffected.",
  "Your muscles freeze in place. Small patterns on rime begin to form on your body. For the next 1d4 hours, your movement speed is halved, but your AC is increased by 2.",
  "You change the weather in a 1 mile radius centered on you. Roll 1d100. On an even number, it begins to rain. On an uneven number, it begins to snow. Regardless of the outcome, the area around you is considered lightly obscured. This effect lasts for 2d12 hours.",
  "Your hands and feet become covered in a thin layer of sticky liquid. You are under the effects of the Spider Climb spell for the next 10 minutes.",
  "You cause hoarfrost to appear on your surroundings (including equipment) in a 30 foot radius around you. This lasts for 1 hour or until removed manually.",
  "You cast Sleet Storm centered on yourself.",
  "You cast the Bones of the Earth spell as a 6th level spell, but the pillars are made of ice. One of the pillars must be under you.",
  "You freeze part of the blood in the creature closest to you. They take 2d10 cold damage and have disadvantage on Strength and Dexterity checks and saving throws for the next 10 minutes or until healed by a spell.",
  "You summon a huge block of ice that falls directly down on you. Each creature within 5 feet of you (including you) must succeed on a Dexterity saving throw against your spell DC, or take 4d10 cold damage. On a success, the damage is reduced to half.",
  "Roll twice on this table and resolve both effects."
]

export default d100cryomancy;
