const d100feyblood = [
  "Roll 1d20. On an even number, you become a mouse with a fur of moss with a vine as tail. On an uneven number, you become an indigo Faerie Dragon. This lasts for 1d4 hours or until your form drops to 0 hit points.",
  "A pair of transparent, glass-like fairy wings appear on your back. You are under the effects of the Fly spell for the next 10 minutes. Every time you cast a spell, the wings flash with a light in a matching color.",
  "Your arms are replaced with vines. You can't perform spells that require a somatic component or carry a weapon. However, your unarmed attacks are replaced by the Grasping Vine spell. This lasts for 10 minutes.",
  "Clusters of goodberries (as from the Goodberry spell) appear along your arms. A total of 2d10+4 berries grow there until harvested or until 1 hour has passed.",
  "You summon a confused Owlbear. After 10 minutes, there's a loud pop and it disappears again.",
  "You switch positions with a random creature within 60 feet of you. As it happens, you both disappear in a puff of pink smoke.",
  "A blue cloud appears over your head and follows you for the next hour. For this duration, the cloud rains colorful confetti and sparkles on you.",
  "Roll 1d100. On an even number, you summon a Pixie and on an uneven number, you summon a Sprite. Regardless of the creature, it's loyal to you and your allies. It disappears after 1 hour or if reduced to 0 hp.",
  "2d10 gold pieces fly from your hands and hit the nearest creature to you. The coins deal 1 bludgeoning damage per gold piece, and you're able to pick them up afterwards.",
  "You grow a beard of moss and leaves. It lasts for 1d4 days or until you sneeze loudly.",
  "A pair of large rabbit ears replace your own ears for 1 hour. You have advantage on all Perception checks relying on hearing.",
  "Every time you attempt to speak, bubbles float out of your mouth instead. When the bubbles are popped, loud opera music can be heard within 100ft of you. This lasts for 2d10 minutes.",
  "Your size is reduced to Tiny for the next 2d10 minutes.",
  "Ethereal voices compliment you loudly every time you perform magic for the next 1d4 hours.",
  "You summon 1d4 Giant Toads who will protect you from anything for the next 2d10 minutes. The Toads each want to be your favorite and if there is no other threat to you will fight each other to be the last one standing.",
  "An eye suddenly appears in the back of your neck. It lasts for 24 hours and you can't be surprised for this duration.",
  "A warm breeze embraces you. You are healed 2d8 hit points.",
  "You cast the Faerie Fire spell centered on yourself. The area of effect for this spell is a 15ft radius, instead of a 20ft cube.",
  "Roll a d20. On an even number, all creatures within 30 feet of you are affected by the Enlarge effect of the Enlarge/Reduce spell. On an odd number, they are affected by the Reduce effect.",
  "You cause an explosion of acid in a 20 foot radius around you. All creatures in the area (including you), must make a Dexterity saving throw against your spell DC. On a failure, the creature takes 2d12 acid damage. The damage is halved on a success.",
  "The next spell you cast will disappear. You still expend the spell slot, and the DM decides when this spell appears and where (and the target, if the spell requires one).",
  "Birds and critters seek you out to tell you secrets they've acquired. You understand them and they understand you for the next hour.",
  "You turn invisible as if under the Invisibility spell. When you become visible, your skin is a bright/neon color. Roll a d8. 1-Red, 2-Orange, 3-Yellow, 4-Green, 5-Blue, 6-Purple, 7-Pink, 8-Rainbow. A remove curse spell can end this effect.",
  "For the next hour, you leave a trail of flowers, fungi and moss behind.",
  "You fall asleep for 1 hour. Only a kiss can wake you from your slumber, Sleeping Beauty!",
  "You summon 1d4 orange Faerie Dragons for the next hour. They are friendly to you and your allies.",
  "A large table appears with a feast on top of it. The DM rolls a d20. On an even number, the food is poisonous and every creature eating it takes 4d8 poison damage and becomes poisoned until their next rest. On an uneven number, the food grants a creature eating it 3d6 temporary hit points and they become immune to being frightened until their next rest. After 1 hour, the table disappears.",
  "Your feet are replaced with goat hooves for 1d4 days. During this time, you have disadvantage on Stealth checks. A remove curse spell can end this effect.",
  "A swarm of ethereal butterflies protect you for the next 10 minutes. During this time, all melee attacks against you have disadvantage. However, you have disadvantage on all Stealth checks.",
  "Antlers sprout from your head. You can make melee weapon attacks with them for 1d8 piercing damage plus your Charisma modifier. The antlers last for 1d4 hours.",
  "You summon an orchestra of spectral instruments. You and your allies gain a bardic inspiration of 1d8.",
  "2 of the potions you carry are now replaced by poisons dealing 3d8 poison damage instead.",
  "Sunlight burns you for 2d6 radiant damage for each minute you stay exposed. This lasts for 10 minutes.",
  "A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "You cast Hypnotic Pattern. The affected area is a 15ft radius centered on you, instead of a cube.",
  "You encase yourself in an orb of glass. While inside, you have total cover from all attacks and spell effects. You can use your action to push against the sphere’s walls and thus roll the sphere at up to half your movement speed. The sphere has an AC of 10, and 5 hit points. The effect ends when the sphere is destroyed.",
  "An extra finger grows on one of your hands. While you have this extra finger, you have advantage on all Sleight of Hand checks and disadvantage on all Persuasion checks. A remove curse spell can end this effect. ",
  "You turn into a tree. While in this form, you have 10 hit points, an AC of 16 and have resistance to all damage, except Fire and Necrotic damage. You have vulnerability to these damage types instead. You are incapacitated while in this form. After 1 hour, or if you drop to 0 hit points you revert back.",
  "You swear that all plants are laughing loudly at you for the next 1d4 hours.",
  "Suction cups appear on your hands and feet. You are affected by the Spider Climb spell for the next hour.",
  "A weapon of your choice within 30 feet of you becomes infused with elemental magic. Roll a d6. (1-Acid, 2-Cold, 3-Fire, 4-Lightning, 5-Poison, 6-Thunder). The weapon is infused for the next hour.",
  "Your hair becomes a bird's nest. An angry bird inhabits this nest for the next hour.",
  "Your skin becomes pearlescent and you gain resistance to fire and radiant damage for the next hour. Additionally, you can cast Cure Wounds as a 1st-level spell once without expending a spell slot.",
  "Your grow fur and your teeth become sharp like a carnivore. You cast Speak With Animals on yourself, with a duration of 1 hour. Additionally, you gain the Natural Weapons feature of the Alter Self spell for 1 hour.",
  "You cast Hallucinatory Terrain right in front of you.",
  "Roll 1d100. On an even number, you age 2d6 years. On an uneven number, you become 2d6 years younger. This effect is permanent, unless you are affected by the Greater Restoration spell - and you are then restored to your original age.",
  "You cast the Blink spell on yourself.",
  "Clusters of colorful fungi appear all over your body. Whenever you, or a creature within 10ft. of you, lies, the fungi glows intensely. After 1 hour, the fungi disappears.",
  "You are under the effect of a Zone of Truth spell for 1d4 days.",
  "Roll twice on this table and resolve both effects."
]

export default d100feyblood;
