const ravenloft = [
  "Until the next dawn, you gain the ability to consume your own fingernails as if they were the fruit of a Goodberry spell. You regrow consumed fingernails after 1d6 days.",
  "Your hair turns bone white. A remove curse spell can end this effect.",
  "You grow mouths on the palms of each hand. A remove curse spell can end this effect.",
  "For the next 2d6 days, horrid pustules grow on your face giving you disadvantage on all Charisma checks, except Intimidation.",
  "For the next hour, you can comprehend all languages but can only speak Abyssal.",
  "A swarm of rats controlled by the DM appears in any unoccupied space within 5 feet of you. (Multiple swarms may be summoned in this manner.)",
  "For the next minute, all non-magical organic objects you touch rot, metal rusts, and food spoils.",
  "You cast animate dead on the nearest corpse within 1 mile.",
  "You see all reflections of yourself as if you were a rotted corpse. A remove curse spell can end this effect.",
  "You become suddenly aware of the horrible truth...if you tear out and consume your left eye, you regain all expended sorcery points.",
  "Your blood becomes a potent material component for your spells. You take 3d10 necrotic damage. The next spell you cast deals maximum damage.",
  "For 1d4 rounds, maggots fall from your mouth when you try to speak, preventing you from talking.",
  "You cast Arms of Hadar as a 1st level spell. You may increase the level the spell is cast at, 1d6 necrotic damage for each level you increase it.",
  "You are chilled and your teeth chatter uncontrollably, giving you disadvantage on Concentration checks for the next 10 minutes.",
  "For an hour, your skin grows dry and scaly. Your AC cannot be below 16 for this time.",
  "You cast Misty Step, bursting into a flock of ravens that reform at the spell's chosen location.",
  "You cast False Life as a 2nd level spell (1d4+9 temporary HP) on yourself.",
  "For the next minute your face becomes pale, your lips blue and your breath white. You may cast Ray of Frost as a bonus action.",
  "Over the next 2d6 days your ears, nose and lips rot off, giving you disadvantage to persuasion checks and advantage to intimidate checks. A remove curse spell can end this effect.",
  "The next time you sleep or meditate, you are afflicted with horrible nightmares or visions and take 1d6 psychic damage when you wake.",
  "You sprout a twisted and useless malformed arm from your side. A remove curse spell can end this effect.",
  "You cast Grasping Vine. It summons a tentacle instead.",
  "You grow a stubby, fleshy, vestigial tail and wings. You can hack them off for 3d6 slashing damage.",
  "For the next minute, you may use the Quickened Spell metamagic expending 1 sorcery point instead of 2. If you do so, you bleed from nose and take 1d6 psychic damage.",
  "Your left arm becomes a tentacle. A remove curse spell can end this effect.",
  "You and all creatures within 30ft are affected by Flesh Rot as if by the contagion spell.",
  "You grow a face on the back of your head. You have advantage on Perception checks, but disadvantage on Concentration checks. A remove curse spell can end this effect.",
  "For the next 2d6 days you smell like rotting meat. The smell worsens and fades over this time.",
  "Your skin becomes cold and clammy. A remove curse spell can end this effect.",
  "Worms erupt from your flesh and knit it together. You heal for 2d10 hit points.",
  "Your skin becomes semi-translucent making your veins and muscles visible. A remove curse spell can end this effect.",
  "For 1d4 rounds your eyes go milk white and you are blind.",
  "You become frightened of the nearest creature for 1d4 rounds.",
  "A ghoul under your control rises from the earth. It is friendly to you and your allies for 1d4 hours, at which point it turns hostile.",
  "For 1d4 days, your teeth grow longer, sharper, and more canine. You pant when you breathe. You gain the Natural Weapons feature of the Alter Self spell.",
  "For the next hour you cast Speak With Dead on all corpses you touch.",
  "Your eyes go black, and you cast the Fear spell. The DM determines the direction of the cone.",
  "You cast Dissonant Whispers as a 1st level spell.",
  "You become an undead creature. You no longer age. You no longer require food, drink, nor air. A remove curse spell can end this effect.",
  "For an hour, your tongue becomes a sentient centipede. You may speak all languages.",
  "You cast Detect Thoughts.",
  "You rapidly gain 3d6 pounds and an equal number of temporary hit points. The weight is lost when the temporary hit points are lost.",
  "You cast Darkness centered on your self.",
  "You cast Hunger of Hadar centered on yourself. You are not blinded by the spell's darkness, and you are resistant to the damage from the spell.",
  "Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.",
  "For the next 24 hours, the next time you are damaged by necrotic damage, you are instead healed that an equal amount.",
  "You age 1d4 years and regain all expended sorcery points.",
  "Reroll on this table. If you do not like the result, you may take 1d6 psychic damage to reroll again. You may reroll like this multiple times, doubling the damage die taken each time. (2d6, 4d6, etc)"
]

export default ravenloft;
