const uad100WildMagicTable = [
  "Roll on this table at the start of each of your turns for the next minute, ignoring this result on subsequent rolls.",
  "Immediately roll twice on this table.",
  "For the next minute, you can see any invisible creature if you have line of sight to it.",
  "You cast Speak with Animals.",
  "A modron chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
  "A mephit chosen and controlled by the DM appears in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
  "You cast Fireball as a 3rd-level spell centered on yourself.",
  "You cast Ice Storm as a 4th-level spell centered on yourself.",
  "You cast Magic Missile as a 5th-level spell.",
  "You cast Scorching Ray as a 5th-level spell.",
  "Roll a d10. Your height changes by a number of inches equal to the roll. If the roll is odd, you shrink. If the roll is even, you grow.",
  "For the next hour, your eyes and veins shed bright light in a 20-foot radius and dim light for an additional 20 feet.",
  "You cast Confusion centered on yourself.",
  "You cast Plant Growth centered on yourself.",
  "For the next minute, you regain 5 hit points at the start of each of your turns.",
  "You cast Aura of Life.",
  "You grow a long beard made of feathers that remains until you sneeze, at which point the feathers explode out from your face.",
  "A daisy sprouts from your head. It may be pruned without harm.",
  "You cast Grease centered on yourself.",
  "You cast Faerie Fire centered on yourself.",
  "Creatures have disadvantage on saving throws against the next spell you cast in the next minute that involves a saving throw.",
  "You have a brief vision of the future. Roll a d20 and record the number rolled. Once in the next hour, you can replace any attack roll, saving throw, or ability check made by you or a creature that you can see with the foretelling roll. You must choose to do so before the roll, and you can replace a roll in this way only once per turn.",
  "Your skin turns a vibrant shade of blue. A Remove Curse spell can end this effect.",
  "You become unable to turn left. A Remove Curse spell can end this effect.",
  "An eye appears on your forehead for the next hour. During that time, you have advantage on Wisdom (Perception) checks that rely on sight.",
  "A glimpse of the future gives you advantage on the next saving throw you make.",
  "For the next minute, all your spells with a casting time of 1 action have a casting time of 1 bonus action.",
  "You cast Haste on yourself.",
  "You teleport up to 60 feet to an unoccupied space that you can see.",
  "You cast Thunder Step as a 3rd-level spell.",
  "You are transported to the Astral Plane until the end of your next turn, after which time you return to the space you previously occupied or the nearest unoccupied space if that space is occupied.",
  "You switch positions with the target immediately after the effects of the spell occurs. If the spell was an area effect, you switch positions with the target closest to you within the effect of the spell.",
  "Maximize the damage of the next damaging spell you cast within the next minute.",
  "For the next minute, when you roll damage for each spell you cast on your turn, you add one additional damage die.",
  "Roll a d10. Your age changes by a number of years equal to the roll. If the roll is odd, you get younger (minimum 1 year old). If the roll is even, you get older.",
  "You take no action on your next turn. Instead, you vomit 1d100 gold pieces.",
  "1d6 flumphs controlled by the DM appear in unoccupied spaces within 60 feet of you and are frightened of you. They vanish after 1 minute.",
  "A pseudodragon controlled by the DM appear in an unoccupied space within 5 feet of you, then disappears 1 minute later.",
  "You regain 2d10 hit points.",
  "You cast Healing Word as 2nd-level spell.",
  "You turn into a potted plant until the start of your next turn. While a plant, you are incapacitated and have vulnerability to all damage. If you drop to 0 hit points, your pot breaks, and your form reverts.",
  "You turn into a harmless, affectionate critter for 1d4-1 (minimum of 1) rounds. While an animal you have a movement speed of 15ft and vulnerability to all damage. If you drop to 0 hit points your form reverts.",
  "For the next minute, you can teleport up to 20 feet as a bonus action on each of your turns.",
  "Spider legs sprout from your back, giving you a climbing speed of 20 ft. The legs remain in place for one hour.",
  "You cast Levitate on yourself.",
  "You cast Freedom of Movement on yourself.",
  "A unicorn controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later. controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "A couatl controlled by the DM appears in a space within 5 feet of you, then disappears 1 minute later.",
  "You can't speak for the next minute. Whenever you try, pink bubbles float out of your mouth.",
  "You're deafened for the next minute. For this duration, green smoke pours out from your ears.",
  "A spectral shield hovers near you for the next minute, granting you a +2 bonus to AC and immunity to Magic Missile.",
  "A Wall of Fire encircles you as a 4th-level spell. You are on the side that takes no damage.",
  "You are immune to being intoxicated by alcohol for the next 5d6 days.",
  "You cast Create Food and Water.",
  "Your hair falls out but grows back within 24 hours.",
  "You shoot eight non-poisonous snakes from your fingertips.",
  "For the next minute, any flammable object you touch that isn't being worn or carried by another creature bursts into flame.",
  "For the next minute, any organic material you touch decays. Food spoils, plants wilt, etc. If you hit a creature with an unarmed strike, you deal an additional 1d4 necrotic damage to it.",
  "You regain your lowest-level expended spell slot.",
  "All silver you are carrying is now gold.",
  "For the next minute, you must shout when you speak.",
  "An illusory image of you is left where you are right now. This can be dispelled with a Dispel Magic spell.",
  "You cast Fog Cloud centered on yourself.",
  "You cast Darkness centered on yourself.",
  "Up to three creatures you choose within 30 feet of you take 4d10 lightning damage.",
  "You breathe a cone of Dragon's Breath as a 2nd-level spell the next time you try to speak.",
  "You are frightened by the nearest creature until the end of your next turn.",
  "You are entombed in crystal, which shatters at the end of your next turn. You gain 50 temporary hit points and you are considered petrified. These effects, including any remaining temporary hit points, all end when the crystal shatters.",
  "Each creature within 30 feet of you becomes invisible for the next minute. The invisibility ends on a creature when it attacks or casts a spell.",
  "For the next minute, creatures within 30 feet of you can't see further than 30 feet away.",
  "You gain resistance to all damage for the next minute.",
  "You cast Warding Wind.",
  "A random creature within 60 feet of you becomes poisoned for 1d4 hours.",
  "A random creature within 60 ft. of you falls asleep for 1d4 rounds or until they take damage. While asleep they are unconscious. A creature is not affected if magic cannot force them to sleep.",
  "You glow with bright light in a 30-foot radius for the next minute. Any creature that ends its turn within 5 feet of you is blinded until the end of its next turn.",
  "You cast Colour Spray as a 1st-level spell.",
  "You cast Polymorph on yourself. If you fail the saving throw, you turn into a sheep for the spell's duration.",
  "You cast Flesh to Stone on yourself.",
  "Illusory butterflies and flower petals flutter in the air within 10 feet of you for the next minute.",
  "Illusory rain and autumn leaves fall to the floor and then vanish within 10 feet of you for the next minute.",
  "You can take one additional action immediately.",
  "If the spell requires concentration, you automatically succeed on all saving throws to maintain it, otherwise it's duration is doubled. If it's instantaneous, it's immediately recast on the same target.",
  "Each creature within 30 feet of you takes 1d10 necrotic damage. You regain hit points equal to the sum of the necrotic damage dealt.",
  "You cast Thunderwave as a 1st-level spell.",
  "You cast Mirror Image.",
  "You cast Blur.",
  "You cast Fly on a random creature within 60 feet of you.",
  "You cast Reverse Gravity centered on yourself.",
  "You become invisible for the next minute. During that time, other creatures can't hear you. The invisibility ends if you attack or cast a spell.",
  "You cast Blink.",
  "If you die within the next minute, you immediately come back to life as if by the Reincarnate spell.",
  "You regain all expended Hit Dice.",
  "Your size increases by one size category for the next minute.",
  "Your size decreases by one size category for the next minute.",
  "You and all creatures within 30 feet of you gain vulnerability to piercing, slashing, or bludgeoning damage for the next minute.",
  "All weapons within 30 ft. of you turns into food for the next minute.",
  "You are surrounded by faint, ethereal music for the next minute.",
  "Gentle gusts of wind blows outward from you for the next minute. All creatures within 40 feet can feel it, but otherwise does nothing.",
  "You regain all expended sorcery points.",
  "For 1 minute, an illusory duplicate of yourself under your control appears on an open space nearest to you. The duplicate takes actions independently, but shares your initiative, health pool, sorcery points, and spell slots. Any resources expended by the duplicate is also expended for you."
]

export default uad100WildMagicTable;
