const homebrewPathOfWildMagic = [
  "You unleash an explosion in a 15-foot radius sphere centered on yourself. Creatures in the area, including you, must make a Dexterity saving throw. An affected creature takes Xd6 (where X is half of your Barbarian level, rounded down) fire damage on a failed save, or half as much damage on a successful one.",
  "Shadowy tendrils lash around you. Each creature of your choice that you can see within 30 feet of you must succeed on a Constitution saving throw or take 1d12 necrotic damage. You also gain 1d12 temporary hit points.",
  "You teleport up to 30 feet to an unoccupied space you can see. Until your rage ends, you can activate this effect again on each of your turns as a bonus action.",
  "An intangible spirit, which looks like a flumph, appears within 5 feet of one creature of your choice that you can see within 30 feet of you. At the end of the current turn, the spirit explodes, and each creature within 5 feet of it must succeed on a Dexterity saving throw or take 1d6 force damage. Until your rage ends, you can use this effect again, summoning another spirit, on each of your turns as a bonus action.",
  "You are borne aloft. Until your rage ends, you gain a flying speed equal to your walking speed.",
  "Whenever a creature hits you with an attack roll before your rage ends, that creature takes 1d6 force damage, as magic lashes out in retribution.",
  "Until your rage ends, you are surrounded by multi­colored, protective lights; you gain a +1 bonus to AC, and while within 10 feet of you, your allies gain the same bonus.",
  "Shadows weave around a weapon of your choice you are holding. Until your rage ends, the weapon’s damage type changes to psychic, and it gains the light and thrown properties, with a normal range of 20 feet and a long range of 60 feet. If the weapon leaves your hand, the weapon reappears in your hand at the end of the current turn.",
  "Cold emanates from your weapon, chilling the air. Until your rage ends, when you hit a creature with a melee weapon attack, it must succeed on a Constitution saving throw or have disadvantage on the next weapon attack roll it makes before the end of its next turn. A creature killed by your attacks becomes a frozen statue until it thaws.",
  "Energy floods into your body. You can immediately take an additional action, which can only be used to take the Attack or Dash action.",
  "A beam of brilliant light lances from your chest. Another creature of your choice that you can see within 60 feet of you must succeed on a Constitution saving throw or take 1d8 radiant damage and be blinded until the start of your next turn. Until your rage ends, you can use this effect again on each of your turns as a bonus action.",
  "Your fingertips crackle with electricity and your hair stands on end. A bolt of lightning arcs out from your hands towards a creature of your choice that you can see within 60 feet. Additional bolts them leap from the target to up to three other creatures of your choosing within 10 feet. All affected creatures must succeed on a Dexterity saving throw or take 1d8 lightning damage.",
  "Roll a d6. A creature corresponding to the result on the Conjure Creature table below appears within an unoccupied space within 5 feet of you. It is friendly towards you and controlled by the DM, and disappears when this effect ends. [1: Flesh Golem, 2: Wood Woad, 3: Hulking Crab, 4: Barlgura, 5: Fire Elemental, 6: Triceratops ]"
]

export default homebrewPathOfWildMagic;
