const d100pyromancy = [
  "You cast the Fireball spell at 4th level centered on yourself.",
  "Choose one of your items. This item is now immune to fire damage (both magical and non-magical).",
  "You summon a horse made from magical flames. It has the stat block of a Nightmare (DMG) and is friendly towards you and your allies for the next hour. You can ride it without taking any damage.",
  "Your hair transforms into flames. It sheds bright light in a 10ft. radius around you, and anyone touching you takes 1d8 fire damage. This effect lasts for 1d10 minutes.",
  "Flaming wings sprout from your back. You gain a flying speed equal to your walking speed for the next 10 minutes.",
  "All flames from your fire spells become black upon casting and make no sound. This magical effect lasts for an hour.",
  "Until you take your next rest (short or long), you can eat hot coal with the same benefits as if eating berries from the Goodberry spell.",
  "You burst into flames. You do not take any damage from this, but all your non-magical items that are not protected from fire damage are destroyed. Each creature within 5ft. of you must make a DC 14 Dexterity saving throw, taking 2d8 fire damage on a failed save. The creature takes no damage on a successful save.",
  "You gain the ability to use a bonus action to disappear in a puff of smoke and teleport 30 feet, as if under the Misty Step spell. This effect lasts for 1d10 minutes.",
  "Your shadow is burnt to ash and disappears. It returns after 1d4 days.",
  "You become immune to fire damage for the next 2d10 minutes.",
  "A gentle light touches your skin. You regain 1d4 Sorcery Points.",
  "You become vulnerable to cold damage for the next 1d4 hours.",
  "You become a red dragonborn for 1d4 hours. If you're already one, you instead become a gold dragonborn for the same duration.",
  "Your hands become engulfed in flames for the next 10 minutes. All your unarmed strikes deal 1d6 + Charisma modifier fire damage.",
  "Four glowing orbs of light swarm around you and insult everyone around you. This lasts 1d10 minutes.",
  "Your ability to cast spells and cantrips with somatic components disappear. However, a flaming sword appears in your hands. On a hit, this deals 3d6 + your Charisma modifier fire damage. This effect lasts 1 minute or until you take cold damage.",
  "Flaming red tattoos appear on everywhere on your body for the next 1d10 minutes. They glow like liquid magma. While this effect is active, your fire spells and cantrips deal an additional 1d4 fire damage.",
  "Roll 1d20. On an even number, you transform into a Magma Mephit, on an odd number, you transform into an Imp. This effect follows the rules of the Polymorph spell, and lasts for 1 hour or you are reduced to 0 hit points.",
  "A burst of glowing fireflies appear and swarm around you, protecting you. This lasts for 1d10 minutes. While this effect is active, you gain a +2 bonus to your Armor Class, though you have disadvantage on Stealth checks.",
  "For the next minute, you absorb all flames around you, including your own. Each time you take fire damage, you can use your reaction to take no damage, and instead heal 1d6 hit points.",
  "Your eyes become filled with pulsing fire. You gain advantage on all Intimidation checks for the next hour.",
  "You cast the Fire Shield spell at 4th level on yourself. This does not require concentration checks when you take damage.",
  "You cast the Magic Missile spell at 3rd level. The missiles look like fireworks.",
  "A Fire Snake (Monster Manual, pg 265) appears in the nearest unoccupied space to you. It is friendly to you and your allies, and disappears after 10 minutes.",
  "All flames from your fire spells become neon blue. For the next hour, your fire spells deal cold damage.",
  "For the next 1d6 hours, you are under the effects of the Death Ward spell. If you die during this time and trigger the spell's effect, you are engulfed in the flaming silhouette of a phoenix.",
  "Your hands become grey like ash. Whenever you touch a metallic object, it's affected by the Heat Metal spell. This effect lasts for 1d4 hours.",
  "An eye engulfed in flames appear on your forehead. You gain 120ft. darkvision and advantage on Perception checks that rely on sight while this is active, but have disadvantage on Stealth and Persuasion checks. This lasts 1 hour.",
  "You cast Scorching Ray as a 3rd spell (4 rays). Each ray must have a different target.",
  "A burning, golden crown adorn your head. You can cast the Command spell for 1d10 minutes as a bonus action without expending a spell slot. Each time you do so, you take 1d6 fire damage.",
  "For the next hour, you leave sets of glowing footprints behind you. They glow with a dim, red light and lasts for 1d4 hours before slowly fading.",
  "Whenever you take damage, you bleed hot magma. Anyone dealing damage to you with a melee attack takes 1d6 fire damage. This lasts 1d4 hours.",
  "Your eyes begin to glow bright like two suns. You are considered Blinded for the next 1d4 minutes.",
  "A gentle warmth spreads throughout your body. You gain 2d10 temporary hit points, which lasts until you take your next rest (short or long).",
  "You have a terrifying vision of a burning city and feel as though you're burning up - your lungs filled with smoke. You take 2d8 psychic damage and become paralyzed until the end of your next turn.",
  "A small fire elemental (Appendix A) appears next to you. It's friendly towards you and your allies, but regards you as it's 'mother' and follows you lovingly. The elemental stays for 1d4 hours. If it survives the whole duration without dropping to 0 hit points, you regain a 2nd level or two 1st level spell slots.",
  "During the next 10 minutes, whenever you open your mouth to speak, you unleash roaring flames from your mouth like the effects of the Dragon's Breath spell. When you unleash this power in combat, it counts as a bonus action.",
  "Your skin becomes black and warm with a texture of burning coal for the next 1d4 hours. During this time, you have resistance to slashing and bludgeoning damage from non-magical sources.",
  "You become afraid of fire for the next 1d10 minutes. Meanwhile, you perceive your allies as large fire elementals and must succeed a Wisdom saving throw against your own spell DC. On a failure, you're frightened of them for the duration of this effect. You can attempt to save again at the end of every turn.",
  "A flaming mirror appears in your hand. While holding this in your hand, you can cast the Scrying spell once without expending a spell slot. Whatever you scry on appears in the mirror.",
  "Massive fiery dragon wings burst from your shoulders. All creatures within 30ft. of you must succeed on a Wisdom saving throw against your spell DC or become frightened of you for 1 minute. A frightened creature can attempt to save at the start of each of their turns.",
  "For the next minute, the damage type of all your spells is changed to fire. ",
  "You cast the Polymorph spell centered on yourself. You turn into a firefly.",
  "Two curled, goat-like horns sprout from your head. They last for the next 1d4 days.",
  "You disappear from your current plane and appear in a pocket dimension. The space is dark and filled with burning braziers. You meet an old tiefling with broken horns named Jirko. He claims, that he knows the answer to any question you might ask. After receiving an answer, you appear where you stood before.",
  "You cast the Faerie Fire spell centered on yourself. The area of effect for this spell is a 15ft radius, instead of a 20ft cube.",
  "You summon a Hell Hound for the next 1d4 hours. It's loyal to you and your allies. It disappears in a puff of black smoke if it's reduced to 0 hit points or when the duration runs out.",
  "You begin to glow with a bright light in a radius of 20ft. around you. After 1 minute, the light explodes, and you take 3d8 radiant damage. Creatures within 20 feet of you must make a Constitution saving throw against your spell save DC, taking 3d8 radiant damage on a failed save, half as much on a success.",
  "Roll twice on this table and resolve both effects."
]

export default d100pyromancy;
