const homebrewPathOfWildMagic = [
  "(Instantenous) You unleash an explosion in a 15-foot radius sphere centered on yourself. Creatures in the area, including you, must make a Dexterity saving throw. An affected creature takes Xd6 (where X is half of your Barbarian level, rounded down) fire damage on a failed save, or half as much damage on a successful one.",
  "(Instantaneous) Necrotic energy bursts from you. Each creature within 30 feet of you takes 1d10 necrotic damage, and you gain temporary hit points equal to the sum of the necrotic damage dealt to the creatures.",
  "(Persistent) You teleport up to 30 feet to an unoccupied space you can see. Until your rage ends, you can activate this effect again on each of your turns as a bonus action.",
  "(Persistent) You are borne aloft. You gain a flying speed equal to your walking speed.",
  "(Instantaneous) Energy floods into your body. You can immediately take an additional action, which can only be used to take the Attack or Dash action.",
  "(Persistent) Cold emanates from your weapon, chilling the air. When you make an attack against a creature, it must succeed on a Constitution saving throw or have disadvantage on the next weapon attack roll it makes before the end of its next turn. A creature killed by your attacks becomes a frozen statue until it thaws.",
  "(Instantaneous) A beam of brilliant light lances from your chest in a 5-foot-wide, 60-foot-long line. Each creature in the line must succeed on a Constitution saving throw or take 2d8 radiant damage and be blinded until the start of your next turn.",
  "(Instantaneous) You conjure 1d4 intangible spirits that look like flumphs in unoccupied spaces within 30 feet of you. Each spirit immediately flies 30 feet in a straight line in directions of your choosing.  At the end of your turn, all spirits explode and each creature within 5 feet of one or more of them must succeed on a Dexterity saving throw or take 2d8 force damage, or half as much on a failed save. If a creature is affected by multiple explosions, they take an extra 1d8 for each extra explosion.",
  "(Persistent) Roll a d6. A creature corresponding to the result on the Conjure Creature table below appears within an unoccupied space within 5 feet of you. It is friendly towards you and controlled by the DM, and disappears when this effecct ends.",
  "(Instantenous) Your fingertips crackle with electricity and your hair stands on end. Two bolts of lightning arc out from your hands towards two creatures of your choosing. Additional bolts then leap from each target to up to three other creatures within 10 feet. Each target must succeed on a Dexterity saving throw or take 2d8 lightning damage.",
  "(Persistent) Shadows weave around a weapon of your choice you are holding. Until your rage ends, your weapon deals psychic damage instead of its bludgeoning, slashing, or piercing damage, and it gains the light and thrown properties with a normal range of 20 feet and a long range of 60 feet. If you drop the weapon or throw it, the weapon dissipates and reappears in your hand at the end of your turn. ",
  "(Persistent) Arcane energy enshrouds you. Until your rage ends, you gain a +2 bonus to AC, and whenever a creature within 10 feet of you hits you with an attack, that creature takes force damage equal to your Constitution modifier."
]

export default homebrewPathOfWildMagic;
