const ravenloft = [
  "You gain the ability to consume your own fingernails as if they were the fruit of a Goodberry spell.",
  "Your hair turns bone white. A remove curse spell can end this effect.",
  "Over the next 2d6 days you grow mouths on the palms of each hand. A remove curse spell can end this effect.",
  "For the next 2d6 days, horrid pustules grow on your face giving you disadvantage on all Charisma checks, except Intimidation.",
  "For the next hour, you can comprehend all languages but can only speak Abyssal.",
  "A swarm of rats appears in any unoccupied space within 5 feet of you.",
  "For the next minute, all non-magic organic objects you touch rot, metal rusts, and food spoils.",
  "You cast animate dead on the nearest corpse within 1 mile.",
  "You see all reflections of yourself as if you were a rotted corpse. A remove curse spell can end this effect.",
  "You become suddenly aware of the horrible truth... if you tear out and consume your left eye, you regain all expended sorcery points.",
  "You cast inflict wounds on yourself. The next spell you cast deals maximum damage.",
  "For 1d4 rounds, maggots fall from your mouth when you try to speak, preventing you from talking.",
  "You cast arms of Hadar as a 1st level spell. You may increase its level and take 1d6 necrotic damage for each rank you increase it.",
  "You are chilled and your teeth chatter uncontrollably, giving you disadvantage on concentration checks for the next 10 minutes.",
  "For an hour, your skin grows dry and scaly. Your AC cannot be below 16 for this time.",
  "You cast misty step, bursting into a flock of ravens that reform at the spell's chosen location.",
  "You cast false life on yourself.",
  "For the next minute your face becomes pale, your lips blue and your breath white. You may cast ray of frost as a bonus action.",
  "Over the next 2d6 days your ears, nose and lips rot off, giving you disadvantage to persuasion checks and advantage to intimidate checks. A remove curse spell can end this effect.",
  "The next time you sleep or meditate, you are afflicted with horrible nightmares or visions and take 1d6 psychotic damage.",
  "You sprout a twisted and useless malformed arm from your side. A remove curse spell can end this effect.",
  "You cast grasping vine. It summons a tentacle instead.",
  "Over the next 2d6 days you grow a stubby, fleshy, vestigial tail and wings. You can hack them off for 3d6 damage.",
  "For the next minute, you may choose to cast spells with casting times of 1 action as if their casting time were 1 bonus action. If you do so, you bleed from nose and take 1d4 psychic damage.",
  "Over the next 2d6 days, your left arm becomes gelatinous and flexible until it becomes a tentacle. A remove curse spell can end this effect.",
  "You and all creatures wit 30' are affected by fleshrot as if by the contagion spell.",
  "Over the next 2d6 days you grow a face on the back of your head that is a warped and useless copy of your own. A remove curse spell can end this effect.",
  "For the next 2d6 days you smell like rotting meat. The smell worsens and fades over this time.",
  "Your skin becomes cold and clammy. A remove curse spell can end this effect.",
  "Worms erupt from your flesh and knit it together. You heal for 2d10 hit points.",
  "Your skin becomes semi-translucent making your veins and muscles visible. A remove curse spell can end this effect.",
  "For 1d4 rounds your eyes go milk white and you are blind.",
  "You become frightened of the nearest creature for 1d4 rounds.",
  "A ghoul under your control rises from the earth. It ceases to be controlled by you in 1d4 hours.",
  "Your teeth grow longer, sharper, and more canine. You pant when you breath. A remove curse spell can end this effect.",
  "For the next hour you cast speak with dead on all corpses you touch.",
  "Your eyes go black, and you cast the Fear spell. The DM determines the direction of the cone.",
  "You cast dissonant whispers on yourself.",
  "For the next 2d6 days you feel compelled to hack up the body of any creature you kill. Take 1d4 psychotic damage each time you kill a creature and do not do this within ten minutes.",
  "For the next minute, each time you lose health, a CR 1/4 swarm of spiders crawls from the wound under your control.",
  "You become an undead creature. You no longer age. You no longer require food, drink, nor air. A remove curse spell can end this effect.",
  "For an hour, your tongue becomes a sentient centipede. You may speak all languages.",
  "You cast detect thoughts. Each time you use your action to focus the spell on a creature, you take 1d4 psychic damage.",
  "You rapidly gain 3d6 pounds and an equal number of temporary hit points. The weight is lost when the temporary hit points are lost.",
  "You cast darkness centered on your self.",
  "You cast hunger of Hadar centered on yourself.",
  "You deal 1d10 necrotic to all creatures within in 30' of you and gain that much health.",
  "For the next 24 hours, the next time you are damaged by necrotic damage, you are instead healed that much health.",
  "You age 1d4 years and regain all expended sorcery points.",
  "Reroll on this table. If you do not like the result, you may take 1d6 psychic damage to reroll again. You may reroll like this multiple times, doubling the damage die taken each time. (2d6, 4d6, etc)"
]

export default ravenloft;
